config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about" , as: 'about'
  get 'searches/search'=>'searches#search', as: 'search'
  get 'chats/show'
#   イイね機能
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
#  フォロー機能 
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get 'chat/:id', to: 'chats#show', as: 'chat'
 resources :chats, only: [:create]
 

  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @books= Book.find(params[:book_id])
    @book_comment = BookComment.new
    @book_comments = BookComment.all
    render  "book_comments"
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
    @book_comment = BookComment.new
    @book_comments = BookComment.all
    render  "book_comments"
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<% book_comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= link_to 'Destroy',book_book_comment_path(comment.book,comment),  method: :delete, remote: true, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
  </tr>
<% end %>

app/views/book_comments/_comment.html.erb
<p>コメント件数：<%= book.book_comments.count %></p>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
    <div class= "form-group">
      <%= f.text_area :comment, placeholder: "コメントをここに", class: "form-control introduction"%>
      <%= f.submit "送信する" %>
    </div>
<% end %>

app/views/book_comments/book_comments.js.erb
$("#comments_area").html("<%= j(render 'book_comments/book_comments',book_comments: @book_comments ) %>");
$(".comment").html("<%= j(render 'book_comments/comment', book: @book ) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');
<!--コントローラーのリダイレクトを変更-->